GG-22736 Backport to 8.8.0 of GG-20891 TableSelfTest - failed with java.lang.NoClassDefFoundError: org/apache/log4j/Layout (#329)
(cherry picked from commit 4946438e54dab825e3ad3e79ecf9632862df5e76)